import { Preset } from '../types';

// よく使うプリセット設定
export const presets: Preset[] = [
  {
    id: 'shogi-wars-3min',
    name: '将棋ウォーズ 3分切れ負け',
    description: '持ち時間3分、切れ負け',
    settings: {
      type: 'basic',
      mainTime: 180,
      byoyomi: 0,
      byoyomiCount: 0,
      considerationTime: 0,
      considerationCount: 0,
      increment: 0,
      movesPerPeriod: 0,
      additionalTime: 0,
    },
  },
  {
    id: 'shogi-wars-10min',
    name: '将棋ウォーズ 10分切れ負け',
    description: '持ち時間10分、切れ負け',
    settings: {
      type: 'basic',
      mainTime: 600,
      byoyomi: 0,
      byoyomiCount: 0,
      considerationTime: 0,
      considerationCount: 0,
      increment: 0,
      movesPerPeriod: 0,
      additionalTime: 0,
    },
  },
  {
    id: 'shogi-10min-30sec',
    name: '将棋 10分+30秒',
    description: '持ち時間10分、秒読み30秒',
    settings: {
      type: 'basic',
      mainTime: 600,
      byoyomi: 30,
      byoyomiCount: 1,
      considerationTime: 0,
      considerationCount: 0,
      increment: 0,
      movesPerPeriod: 0,
      additionalTime: 0,
    },
  },
  {
    id: 'nhk-cup',
    name: 'NHK杯ルール',
    description: '持ち時間10分、秒読み30秒、考慮時間60秒×10回',
    settings: {
      type: 'consideration',
      mainTime: 600,
      byoyomi: 30,
      byoyomiCount: 1,
      considerationTime: 60,
      considerationCount: 10,
      increment: 0,
      movesPerPeriod: 0,
      additionalTime: 0,
    },
  },
  {
    id: 'abema-tournament',
    name: 'ABEMAトーナメント',
    description: '持ち時間5分、フィッシャー5秒加算',
    settings: {
      type: 'fischer',
      mainTime: 300,
      byoyomi: 0,
      byoyomiCount: 0,
      considerationTime: 0,
      considerationCount: 0,
      increment: 5,
      movesPerPeriod: 0,
      additionalTime: 0,
    },
  },
  {
    id: 'chess-bullet-1min',
    name: 'チェス バレット 1分',
    description: '持ち時間1分、切れ負け',
    settings: {
      type: 'basic',
      mainTime: 60,
      byoyomi: 0,
      byoyomiCount: 0,
      considerationTime: 0,
      considerationCount: 0,
      increment: 0,
      movesPerPeriod: 0,
      additionalTime: 0,
    },
  },
  {
    id: 'chess-blitz-3min',
    name: 'チェス ブリッツ 3分',
    description: '持ち時間3分、切れ負け',
    settings: {
      type: 'basic',
      mainTime: 180,
      byoyomi: 0,
      byoyomiCount: 0,
      considerationTime: 0,
      considerationCount: 0,
      increment: 0,
      movesPerPeriod: 0,
      additionalTime: 0,
    },
  },
  {
    id: 'chess-blitz-5min',
    name: 'チェス ブリッツ 5分',
    description: '持ち時間5分、切れ負け',
    settings: {
      type: 'basic',
      mainTime: 300,
      byoyomi: 0,
      byoyomiCount: 0,
      considerationTime: 0,
      considerationCount: 0,
      increment: 0,
      movesPerPeriod: 0,
      additionalTime: 0,
    },
  },
  {
    id: 'chess-rapid-10-5',
    name: 'チェス ラピッド 10+5',
    description: '持ち時間10分、5秒加算',
    settings: {
      type: 'fischer',
      mainTime: 600,
      byoyomi: 0,
      byoyomiCount: 0,
      considerationTime: 0,
      considerationCount: 0,
      increment: 5,
      movesPerPeriod: 0,
      additionalTime: 0,
    },
  },
  {
    id: 'chess-rapid-15-10',
    name: 'チェス ラピッド 15+10',
    description: '持ち時間15分、10秒加算',
    settings: {
      type: 'fischer',
      mainTime: 900,
      byoyomi: 0,
      byoyomiCount: 0,
      considerationTime: 0,
      considerationCount: 0,
      increment: 10,
      movesPerPeriod: 0,
      additionalTime: 0,
    },
  },
  {
    id: 'chess-classical-90-30',
    name: 'チェス クラシカル 90+30',
    description: '持ち時間90分、30秒加算',
    settings: {
      type: 'fischer',
      mainTime: 5400,
      byoyomi: 0,
      byoyomiCount: 0,
      considerationTime: 0,
      considerationCount: 0,
      increment: 30,
      movesPerPeriod: 0,
      additionalTime: 0,
    },
  },
  {
    id: 'go-30min-30sec',
    name: '囲碁 30分+30秒',
    description: '持ち時間30分、秒読み30秒',
    settings: {
      type: 'basic',
      mainTime: 1800,
      byoyomi: 30,
      byoyomiCount: 1,
      considerationTime: 0,
      considerationCount: 0,
      increment: 0,
      movesPerPeriod: 0,
      additionalTime: 0,
    },
  },
  {
    id: 'go-byoyomi-multi',
    name: '囲碁 秒読み5回',
    description: '持ち時間10分、秒読み30秒×5回',
    settings: {
      type: 'byoyomi_multi',
      mainTime: 600,
      byoyomi: 30,
      byoyomiCount: 5,
      considerationTime: 0,
      considerationCount: 0,
      increment: 0,
      movesPerPeriod: 0,
      additionalTime: 0,
    },
  },
  {
    id: 'canadian-5min-25-5',
    name: 'カナダ式 5分+25手5分',
    description: '持ち時間5分、25手ごとに5分追加',
    settings: {
      type: 'canadian',
      mainTime: 300,
      byoyomi: 0,
      byoyomiCount: 0,
      considerationTime: 0,
      considerationCount: 0,
      increment: 0,
      movesPerPeriod: 25,
      additionalTime: 300,
    },
  },
];

// プリセットをIDで検索
export function getPresetById(id: string): Preset | undefined {
  return presets.find(p => p.id === id);
}

